name: CI
on:
  push:
   branches: [main]
  pull_request:
    branches: [main]
jobs:
  dagger-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        
      - name: Run dagger functions
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: "call"
          args: ci --source=. --infisical-client-id env:INFISICAL_CLIENT_ID --infisical-client-secret env:INFISICAL_CLIENT_SECRET --infisical-project-id "6eb5705a-ff7b-4a24-9c2f-abc519975099"
